name: Execute Automation Build
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  run_sh_and_compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Run Single File Automation Project Creator
      run: |
        chmod +x build_app.sh
        ./build_app.sh

    - name: Setup Java Environment
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile Real APK Now
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: ATM-NEET-LOCKDOWN-SINGLE-FILE-BUILD
        path: app/build/outputs/apk/debug/app-debug.apk
